### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by kmamal** [EftyK/TrainedModel#1]
containEs -> contains

To repo summary leei akoma "which is aimed to identify"

"model, for" -> "model for" xwris komma

" loads a trained tensorflow model visualizes" -> loads THE trained tensorflow model AND visualizes

"label map and some" -> "label map, and some" oxford comma

mou arese pou ta eixes se lista ta prerequisites. ase kai thn lista kai tis entoles

Download or git clone [this](https://github.com/tensorflow/models) repository. -> Download or git clone the [tensorflow/models](https://github.com/tensorflow/models) repository.

This should end in -> this should result in

Navigate in -> Navigate to

**Comment by EftyK** [comment]
Thanks for the attention.

**Comment by kmamal** [comment]
attention -> help
